### ISSUE TITLE
Some question help

### ISSUE THREAD

**Issue by marksev1** [GermanBluefox/node-red-vis#15]
Hello,

with regular Node-red, not with IObroker, how would I make this work: https://www.npmjs.com/package/iobroker.vis-lcars 
https://github.com/ioBroker/ioBroker.vis-lcars ? :)

So I could have LCARS interface instead of normal one... :)

**Comment by marksev1** [comment]
Ping.

**Comment by GermanBluefox** [comment]
It is strange, normally you should have the widgets set installed. and you can use it like this.
Which widget sets can you see?
![image](https://cloud.githubusercontent.com/assets/4582016/20284520/c068322c-aabd-11e6-95c0-ecdc8c817f9d.png)

**Comment by marksev1** [comment]
I see them thank you! Closing issue :).

**Comment by marksev1** [comment]
Tho' if i try the demo with the demo flow I don't get any data inside the debug panel of the node-red....hmmm..

**Comment by gillerman** [comment]
Thank you for looking into this.

**Comment by marksev1** [comment]
Also I would be interested on where to find the LCARS demo UI the whole one, like its on the iobroker forum?

**Comment by gillerman** [comment]
Here are my note about getting Node-RED working with SVG:

How to access the msg object from browser JavaScript
To access the msg from script and also to run scripts when the msg changes though it isn't exactly an obvious process! The following code will enable you to see what is going on and should be enough to let you write your own scripts:
{{msg.payload}}

<script>
    (function(scope) {
        console.log('Position 1');
        console.dir(scope);
        scope.$watch('msg.payload', function(data) {
            console.log('Position 2');
            console.dir(data);
        });
    })(scope);
</script>

Similarly,

<script>
(function(scope) {
    scope.$watch('msg.payload', function() {
        console.log('payload: ' + scope.msg.payload)
    })
})(scope)
</script>

Push some data into the template, switch to the Dashboard UI page and open your browser's console with F12. You will see on the console output "Position 1" followed by the letter "b" (I've no idea why "b"!), this is the scope object and you can see that the scope object APPEARS to contain the msg object. Not so quick! Actually, when calling the console.dir(scope); line, the msg object does NOT exist, it appears to only because of the way the browser outputs the console commands. The reason for this is understood by looking at the next part.
What this does is to set a watch on the scope object for a sub-object scope.msg.payload, you will note from the console output that this is actually triggered twice and only on the second time is scope.msg.payload actually defined.  I'm not entirely certain why this happens but I think it is something to do with the way that Angular works. So don't forget to check that the watched object contains something useful before relying on it being there.
Anyway, the bottom line is that you can use the watch function to monitor the msg.payload (or of course the whole msg or something else suitable). The function will be triggered whenever you update the msg. Try having two inject nodes into the same template with different payloads and you will see what I mean. Each time you trigger, you will get a new console message - but ONLY if the payload actually changes, sending the same text twice for example will only trigger the function once.
Sending and receiving messages to/from javascript in Dashboard Template node
This is a simple flow demonstrating how to send messages to javascript in a Dashboard Template node and how to send messages back to the flow from javascript. In addition it shows how to send a message to node-red when the view is opened in a browser, which is useful for preloading data into the view when it is first opened. As is shown in the flow below, exactly the same code can be used in two templates, each picking up messages from node-red and sending responses back.

<p>{{msg.payload}}</p>

<script>
(function() {
    var count = 0
    function testit(msg,scope) {
        count = count+1;
        console.log("In testit " + msg.payload + "  count = " + count);
        scope.send({payload: "from testit " + msg.payload + "  count = " + count});
    }
    (function(scope) {
        scope.send({payload: "preload"});   // this gets sent when the view is opened in the browser
        scope.$watch('msg', function(msg) {
            if (msg) {
                testit(msg, scope);
            }
        });
    })(scope);
})();
</script>

Sending and receiving messages to/from d3 JavaScript in a Dashboard Template node

<style>
#chart svg {
  width: 800px;
  height: 600px;
}
</style>

<h3>test</h3>

<div id="chart">
  <svg></svg>
</div>

<script src="https://raw.githubusercontent.com/novus/nvd3/master/build/nv.d3.js"></script>

<script>
    (function(scope) {
        console.log('Position 1');
        console.dir(scope);
        console.log(scope.msg);
        scope.$watch('msg.payload', function(data) {
            console.log('Position 2');
            console.dir(data);
        });
    })(scope);
function data() {
  var sin = [],
      cos = [];
  for (var i = 0; i < 100; i++) {
    sin.push({x: i, y: Math.sin(i/10)});
    cos.push({x: i, y: .5 * Math.cos(i/10)});
  }
  return [
    {
      values: sin,
      key: 'normal',
      color: '#ff7f0e'
    },
    {
      values: cos,
      key: 'defect',
      color: '#2ca02c'
    }
  ];
}
nv.addGraph(function() {
  var chart = nv.models.lineChart()
    .useInteractiveGuideline(true);
  chart.xAxis
    .axisLabel('frequence')
    .tickFormat(d3.format(',r'));
  chart.yAxis
    .axisLabel('amplitude')
    .tickFormat(d3.format('.02f'));
  d3.select('#chart svg')
    .datum(data())
    .transition().duration(500)
    .call(chart);
  nv.utils.windowResize(chart.update);
  return chart;
});
</script>

Global context
There is also a global context available that is shared by, and accessible to all nodes. For example to make the variable foo available globally across the canvas:
global.set("foo","bar");  // this is now available to other nodes
var myfoo = global.get("foo");  // And can then be read using .get This should now be "bar"
The global context can also be pre-populated with objects when Node-RED starts. This is defined in the main settings.js file under the functionGlobalContext property.

<script id="titleScript" type="text/javascript">
    $('#titleScript').parent().hide();
    var toolbar = $('.md-toolbar-tools');
    var div = $('<div/>');
    var p = $('<p/>');
    div.append(p);
    div[0].style.margin = '5px 5px 5px auto';
    function displayTitle(lh) {
       p.text(lh);
    }
    toolbar.append(div);
    // Watch the payload and update the title
    (function(scope) {
        scope.$watch('msg.payload', function(data) {
            displayTitle(data);
        });
    })(scope);
</script>

**Comment by marksev1** [comment]
Wow looks very hard.

**Comment by gillerman** [comment]
This code is close to working:

<div ng-model="msg.payload">
<svg class="classVP"></svg>
<script src="d3/d3.v3.min.js"></script>
<script>
var vpWidth = 100, vpHeight = 50;
var barWidth = 0;
(function loadData (scope) {
   scope.$watch('msg.payload', function(barWidth)
       {
           displayRect(barWidth)
       })
})(scope)
function displayRect(bw){
   var data = [1];
   var myVP = d3.select(".classVP")
                .attr("width", vpWidth)
                .attr("height", vpHeight);
   var bar = myVP.selectAll("g")
                .data(data)
                .enter().append("g")
             bar.append("rect")
                .attr("width", bw)
                .attr("height", vpHeight - 10)
                .attr("fill", "blue");
   console.log('barWidth: ' + bw)
}
</script>
</div>

**Comment by marksev1** [comment]
So this I should put into template node and connect to vis node? Could you post the entire node-red flow maybe please?

**Comment by gillerman** [comment]
This code works:

<div ng-model="msg.payload">
<svg class="classVP"></svg>
<script type="text/javascript" src="d3\d3.min.js"></script>
<script>
var vpWidth = 100, vpHeight = 50;
    var data = [1];
    var myVP = d3.select(".classVP")
                 .attr("width", vpWidth)
                 .attr("height", vpHeight);
    var bar = myVP.selectAll("g")
                 .data(data)
                 .enter().append("g")
              bar.append("rect")
                 .attr("x", 10)
                 .attr("y", 10)
                 .attr("width", 50)
                 .attr("height", vpHeight - 10)
                 .attr("fill", "yellow");
(function loadData (scope) {
    scope.$watch('msg.payload', function(color)
        {
            updateRect(color)
        })
})(scope)
function updateRect(clr){
    var r = d3.select(".classVP").select("g").select("rect")
        r.attr("fill", clr);
        console.log('r: ' + d3.select(".classVP").select("g").select("rect").attr("fill"))
        console.log('color: ' + clr)
}
</script>
</div>

**Comment by marksev1** [comment]
Can you post example flow please, because I don't know how i should use this code?

Is it possible to set that the button changes color when I toggle it (LCARS vis buttons)?

**Comment by gillerman** [comment]
[{"id":"2f635cee.80ecd4","type":"ui_button","z":"29288854.03af38","name":"Green","group":"b7c9949.a48fa68","order":0,"width":"2","height":"1","label":"Green","color":"","icon":"","payload":"green","payloadType":"str","topic":"color","x":584.9999847412109,"y":91,"wires":[["3ca2d9e2.f5f346"]]},{"id":"3ca2d9e2.f5f346","type":"ui_template","z":"29288854.03af38","group":"b7c9949.a48fa68","name":"ColorRect","order":0,"width":0,"height":0,"format":"<div ng-model=\"msg.payload\">     \n<svg class=\"classVP\"></svg>\n<script type=\"text/javascript\" src=\"d3\\d3.min.js\"></script>\n\n<script>\nvar vpWidth = 100, vpHeight = 50;\n    var data = [1];\n    var myVP = d3.select(\".classVP\")\n                 .attr(\"width\", vpWidth)\n                 .attr(\"height\", vpHeight);\n    var bar = myVP.selectAll(\"g\")\n                 .data(data)\n                 .enter().append(\"g\")\n              bar.append(\"rect\")\n                 .attr(\"x\", 10)\n                 .attr(\"y\", 10)\n                 .attr(\"width\", 50)\n                 .attr(\"height\", vpHeight - 10)\n                 .attr(\"fill\", \"yellow\");\n                 \n(function loadData (scope) {\n    scope.$watch('msg.payload', function(color) \n        {\n            updateRect(color)\n        })\n})(scope)\n\n\nfunction updateRect(clr){\n    var r = d3.select(\".classVP\").select(\"g\").select(\"rect\")\n        r.attr(\"fill\", clr);\n        console.log('r: ' + d3.select(\".classVP\").select(\"g\").select(\"rect\").attr(\"fill\"))\n        console.log('color: ' + clr)\n}\n</script>\n</div>\n\n\n\n\n ","storeOutMessages":false,"fwdInMessages":false,"x":772.3332977294922,"y":72.33332824707031,"wires":[[]]},{"id":"75c13f81.2cc64","type":"ui_button","z":"29288854.03af38","name":"Blue","group":"b7c9949.a48fa68","order":0,"width":"2","height":"1","label":"Blue","color":"","icon":"","payload":"blue","payloadType":"str","topic":"color","x":586.9999847412109,"y":54,"wires":[["3ca2d9e2.f5f346"]]},{"id":"b7c9949.a48fa68","type":"ui_group","z":"","name":"d3","tab":"7008b9bd.de4b88","order":1,"disp":true,"width":"15"},{"id":"7008b9bd.de4b88","type":"ui_tab","z":"","name":"Test","icon":"dashboard","order":2}]

**Comment by marksev1** [comment]
Edit: disregard previous post, its valid :).

**Comment by gillerman** [comment]
What version of Node-RED and the dashboard are you using?

[{"id":"2f635cee.80ecd4","type":"ui_button","z":"29288854.03af38","name":"Green","group":"b7c9949.a48fa68","order":0,"width":"2","height":"1","label":"Green","color":"","icon":"","payload":"green","payloadType":"str","topic":"color","x":584.9999847412109,"y":91,"wires":[["3ca2d9e2.f5f346"]]},{"id":"3ca2d9e2.f5f346","type":"ui_template","z":"29288854.03af38","group":"b7c9949.a48fa68","name":"ColorRect","order":0,"width":0,"height":0,"format":"<div ng-model=\"msg.payload\">     \n<svg class=\"classVP\"></svg>\n<script type=\"text/javascript\" src=\"d3\\d3.min.js\"></script>\n\n<script>\nvar vpWidth = 100, vpHeight = 50;\n    var data = [1];\n    var myVP = d3.select(\".classVP\")\n                 .attr(\"width\", vpWidth)\n                 .attr(\"height\", vpHeight);\n    var bar = myVP.selectAll(\"g\")\n                 .data(data)\n                 .enter().append(\"g\")\n              bar.append(\"rect\")\n                 .attr(\"x\", 10)\n                 .attr(\"y\", 10)\n                 .attr(\"width\", 50)\n                 .attr(\"height\", vpHeight - 10)\n                 .attr(\"fill\", \"yellow\");\n                 \n(function loadData (scope) {\n    scope.$watch('msg.payload', function(color) \n        {\n            updateRect(color)\n        })\n})(scope)\n\n\nfunction updateRect(clr){\n    var r = d3.select(\".classVP\").select(\"g\").select(\"rect\")\n        r.attr(\"fill\", clr);\n        console.log('r: ' + d3.select(\".classVP\").select(\"g\").select(\"rect\").attr(\"fill\"))\n        console.log('color: ' + clr)\n}\n</script>\n</div>\n\n\n\n\n ","storeOutMessages":false,"fwdInMessages":false,"x":772.3332977294922,"y":72.33332824707031,"wires":[[]]},{"id":"75c13f81.2cc64","type":"ui_button","z":"29288854.03af38","name":"Blue","group":"b7c9949.a48fa68","order":0,"width":"2","height":"1","label":"Blue","color":"","icon":"","payload":"blue","payloadType":"str","topic":"color","x":586.9999847412109,"y":54,"wires":[["3ca2d9e2.f5f346"]]},{"id":"b7c9949.a48fa68","type":"ui_group","z":"","name":"d3","tab":"7008b9bd.de4b88","order":1,"disp":true,"width":"15"},{"id":"7008b9bd.de4b88","type":"ui_tab","z":"","name":"Test","icon":"dashboard","order":2}]

**Comment by marksev1** [comment]
Gillerman are you trolling me, I don't need some square changing color, i'd like to connect node-red-vis dashboard with debug inside node-red?

**Comment by gillerman** [comment]
I don’t think I have ever been accused of trolling anyone ever before.  I had thought you wanted to run your visualization within a node-red dashboard.  The code I sent you shows you how a Node-RED template can receive an event and then do subsequent processing using d3.  But I think you are correct, we seem to have reached a point of diminishing returns.

**Comment by marksev1** [comment]
I will close this issue for now.
